name: DNNGP3
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20210324.2=h2531618_0
  - absl-py=1.3.0=py39h06a4308_0
  - aiohttp=3.8.3=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - astor=0.8.1=py39h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39h06a4308_0
  - attrs=22.1.0=py39h06a4308_0
  - blas=1.0=mkl
  - blinker=1.4=py39h06a4308_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda-nvcc=12.1.66=0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1=cuda11.3_0
  - flatbuffers=2.0.0=h2531618_0
  - flit-core=3.8.0=py39h06a4308_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h5eee18b_3
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py39hce63b2e_0
  - h5py=3.7.0=py39h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=68.1=h2531618_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.1=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - keras=2.6.0=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.19.4=h568e23c_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.88.1=h91b91d3_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.14.0=h8c45485_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - markdown=3.4.1=py39h06a4308_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=6.0.2=py39h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.4=py39he184ba9_0
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - oauthlib=3.2.2=py39h06a4308_0
  - openssl=1.1.1t=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.0=py39h06a4308_0
  - pandas=1.5.2=py39h417a72b_0
  - pip=23.0.1=py39h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - protobuf=3.14.0=py39h2531618_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39h06a4308_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - pytz=2022.7=py39h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.2.1=py39h6a678d5_0
  - scipy=1.10.0=py39h14f4228_1
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.1=h5eee18b_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.1=py39h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py39h06a4308_0
  - tensorflow=2.6.0=mkl_py39haac40d1_0
  - tensorflow-base=2.6.0=mkl_py39h3d85931_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=2.1.0=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - werkzeug=2.2.3=py39h06a4308_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h5eee18b_0
  - xz=5.2.10=h5eee18b_1
  - yarl=1.8.1=py39h5eee18b_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - tensorflow-probability==0.14.0
      - framework-reproducibility==0.4.0

